// <auto-generated />
using System;
using DerivcoAssessment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DerivcoAssessment.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240513135948_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("DerivcoAssessment.Models.Bet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int?>("BetResult")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BetStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Colour")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PayoutId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SpinId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PayoutId");

                    b.HasIndex("SpinId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("DerivcoAssessment.Models.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int?>("BetResult")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SpinId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpinId");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("DerivcoAssessment.Models.Spin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Colour")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Spins");
                });

            modelBuilder.Entity("DerivcoAssessment.Models.Bet", b =>
                {
                    b.HasOne("DerivcoAssessment.Models.Payout", "Payout")
                        .WithMany()
                        .HasForeignKey("PayoutId");

                    b.HasOne("DerivcoAssessment.Models.Spin", "Spin")
                        .WithMany()
                        .HasForeignKey("SpinId");

                    b.Navigation("Payout");

                    b.Navigation("Spin");
                });

            modelBuilder.Entity("DerivcoAssessment.Models.Payout", b =>
                {
                    b.HasOne("DerivcoAssessment.Models.Spin", "Spin")
                        .WithMany()
                        .HasForeignKey("SpinId");

                    b.Navigation("Spin");
                });
#pragma warning restore 612, 618
        }
    }
}
